language: csharp
solution: libsodium-core.sln

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: false
      dotnet: 2.2
      mono: none
      env: DOTNET_VERSION=netcoreapp2.1
    - os: linux
      dist: xenial
      sudo: false
      dotnet: 3.1
      mono: none
      env: DOTNET_VERSION=netcoreapp3.1
    - os: osx
      osx_image: xcode11.3
      dotnet: 2.1.300
      mono: none
      env: DOTNET_VERSION=netcoreapp2.1
    - os: osx
      osx_image: xcode11.3
      dotnet: 3.1.100
      mono: none
      env: DOTNET_VERSION=netcoreapp3.1

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.nuget/packages

before_install:
  - git config --global core.autocrlf input
  - ulimit -n 1024

#install:
#  - dotnet restore --disable-parallel -r $TRAVIS_OS_NAME-x64

script:
  - dotnet test test/Sodium.Tests/Sodium.Tests.csproj --framework $DOTNET_VERSION
